name: Moonshae Isles
theme: jekyll-theme-modernist

title: <a href="https://kevc13.github.io/Moonshae-Isles/">Moonshae Isles Campaign Page</a>
description: A recap of our playthrough of the Moonshae Isles campaign
